spring:
    application:
        name: pastex
    jpa:
        show-sql: false
        properties:
            hibernate:
                format_sql: false
    flyway:
        enabled: true
        locations: classpath:db/migration